export const CordSquar = [ 
    { CoX:0, CoY:0},
    { CoX:1, CoY:0},
    { CoX:2, CoY:0},
    { CoX:3, CoY:0},
    { CoX:4, CoY:0},
    { CoX:0, CoY:1},
    { CoX:1, CoY:1},
    { CoX:2, CoY:1},
    { CoX:3, CoY:1},
    { CoX:4, CoY:1},
    { CoX:0, CoY:2},
    { CoX:1, CoY:2},
    { CoX:2, CoY:2},
    { CoX:3, CoY:2},
    { CoX:4, CoY:2},
    { CoX:0, CoY:3},
    { CoX:1, CoY:3},
    { CoX:2, CoY:3},
    { CoX:3, CoY:3},
    { CoX:4, CoY:3},
    { CoX:0, CoY:1},
    { CoX:1, CoY:1},
    { CoX:2, CoY:1},
    { CoX:3, CoY:1},
    { CoX:4, CoY:1}, ]